apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app

  template:
    metadata:
      labels:
        app: app
    spec:
      containers: 
      - name: educacenter-apache
        image: docker.io/pweslly/apache
        ports:
        - containerPort: 80 